name: zam_factory_pattern
version: 0.0.1
description: Provides utilities to implement the factory pattern which deals
  with the problem of creating objects.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_factory_pattern

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  zam_core: ^0.1.1

dev_dependencies:
  zam_test: ^0.1.0
