name: zam_factory_pattern
version: 0.2.0
description: Provides utilities to implement the factory pattern which deals
  with the problem of creating objects.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_factory_pattern

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  zam_core: ^0.7.0

dev_dependencies:
  lints: ^2.0.0
  zam_test: ^0.5.0
